// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Shutdown() {
  return window['go']['app']['App']['Shutdown']();
}

export function Start(arg1) {
  return window['go']['app']['App']['Start'](arg1);
}
